version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/todo_app'
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
