name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-express-app .

      - name: Start Docker Compose
        run: docker-compose up -d

      

      - name: Deploy to Production
        run: |
          # Your deployment commands here

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image with tag 'latest'
        run: |
          docker pull thowfeeksalim/todo:latest

      - name: Build and Push Docker image
        id: docker_build
        run: |
          docker build . --file Dockerfile --tag thowfeeksalim/todo
          docker push thowfeeksalim/todo

      - name: Check for errors
        if: steps.docker_build.outcome != 'success'
        run: |
          echo "An error occurred during image build and push."
          exit 1
