name: Build, Push, and Restart Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest code
        run: |
          git pull origin master

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t thowfeeksalim/docker-old .
          docker push thowfeeksalim/docker-old

      - name: Restart Locally
        run: |
          docker stop edee883d5e36
          docker stop 0e6c07f668e2
          docker pull thowfeeksalim/docker-old:latest
          docker-compose -f C:\jul\docker-old\docker-compose.yml up -d
          docker compose up --build --detach
          docker run -d thowfeeksalim/docker-old:latest

