name: Build, Push Docker Image, and Upload docker-compose.yml

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t thowfeeksalim/docker-old .
          docker push thowfeeksalim/docker-old

      - name: Upload docker-compose.yml to Docker Hub
        run: |
          docker run --rm -v $PWD:/workdir -w /workdir alpine sh -c "cp docker-compose.yml  /docker-compose.yml"
