jobs:
  self-hosted-docker:
    name: test
    runs-on: self-hosted   

steps:
  - name: Check out repository code
    uses: actions/checkout@v2

  - name: Run PowerShell as administrator
    shell: pwsh
    run: |
      # Set PowerShell execution policy as bypass
      Set-ExecutionPolicy Bypass -Scope Process -Force
  - name: Pull the latest Docker image
    run: docker pull thowfeeksalim/docker-old:latest

  - name: Start Docker Compose services
    run: docker-compose up --build --detach

  - name: Run Docker container in detached mode
    run: docker run -d thowfeeksalim/docker-old:latest
