name: test

on:
  push:
    branches:
      - master

jobs:
  self-hosted-docker:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Pull the latest Docker image
        run: docker pull thowfeeksalim/docker-old:latest

      - name: Start Docker Compose services
        run: docker-compose up --build --detach

      - name: Run Docker container in detached mode
        run: docker run -d thowfeeksalim/docker-old:latest
