name: test

on:
  push:
    branches:
      - master

jobs:
  self-hosted-docker:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
          
      - name: Run PowerShell command
        shell: pwsh
        run: |
          docker pull thowfeeksalim/docker-old:latest
          docker-compose up --build --detach
          docker run -d thowfeeksalim/docker-old:latest
