jobs:
  self-hosted-docker:
    name: Self-Hosted Docker Task
    runs-on: self-hosted   # Make sure you have a self-hosted runner configured for this workflow

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull thowfeeksalim/docker-old:latest

      - name: Run Docker Compose
        run: docker-compose up --build --detach

      - name: Run Docker container
        run: docker run -d thowfeeksalim/docker-old:latest

      - name: Run PowerShell as administrator
        shell: pwsh
        run: |
          # Your PowerShell commands as administrator here
          Set-ExecutionPolicy Bypass -Scope Process -Force
          # Run any administrative PowerShell commands you need

